### ISSUE TITLE
Does not run on rails 4.2.6

### ISSUE THREAD

**Issue by kvokka** [hyperoslo/activeadmin_polymorphic#16]
I try out to add gem functionality, but gut an issue (below). Maybe I'm wrong somewhere, but I follow the docs and all works good in console. 

So, I have:

```
class AbstractModel < ActiveRecord::Base
  self.abstract_class = true
  has_many :configs, as: :configurable
end

class Config < AbstractModel
  belongs_to :configurable, polymorphic: true
  accepts_nested_attributes_for :configurable
end
```

All bu models inherit from `AbstractModel` so, i have ability to use association with all my classes.
In ActiveAdmin I post:

```
ActiveAdmin.register Config do
  permit_params :title, :internal_name, :configurable, :configurable_id, :configurable_type

  filter :title
  form builder: ActiveadminPolymorphic::FormBuilder do |f|
    f.semantic_errors(*f.object.errors.keys)
    f.inputs do
      f.input :title
      f.input :internal_name
      SECTIONABLES = [PriceList, Hall]
      f.polymorphic_has_many :configs, :configurable, types: SECTIONABLES
    end
    f.actions
  end
end
```

trace log:

```
Completed 500 Internal Server Error in 1731ms (ActiveRecord: 13.0ms)

NoMethodError - undefined method `configurable' for nil:NilClass:
  activeadmin_polymorphic (0.3.4) lib/activeadmin_polymorphic/form_builder.rb:105:in `block in polymorphic_form'
  formtastic (3.1.4) lib/formtastic/helpers/inputs_helper.rb:376:in `block (2 levels) in inputs_for_nested_attributes'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  formtastic (3.1.4) lib/formtastic/helpers/fieldset_wrapper.rb:32:in `field_set_and_list_wrapping'
  formtastic (3.1.4) lib/formtastic/helpers/inputs_helper.rb:293:in `inputs'
  formtastic (3.1.4) lib/formtastic/helpers/inputs_helper.rb:374:in `block in inputs_for_nested_attributes'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.6) lib/action_view/helpers/form_helper.rb:714:in `fields_for'
...
```

I can provide all other needed information and I'll be very pleased for your answer.

**Comment by toothfairy** [comment]
Hey @kvokka, nice avatar :) 

I'll try to take a look at this on weekend. Thanks for report

**Comment by jgorset** [comment]
@toothfairy is such a cool guy.

**Comment by toothfairy** [comment]
@kvokka it seems you have different models structure, than it required by design.
<img width="701" alt="68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f325a334d32563062335a3334324c325a3252304e2f53637265656e25323053686f74253230323031352d30322d3035253230617425323031332e33372e33362e706e67" src="https://cloud.githubusercontent.com/assets/725806/14587799/de554f36-04b9-11e6-847a-ac1c462ccee9.png">

Take a looks at this one, there is proxy model to connect your models.

**Comment by kvokka** [comment]
Thank you. So close it, I decide my problem manually :)

**Comment by toothfairy** [comment]
Thank you too @kvokka
